services:
  app:
    build:
      context: ./app
      dockerfile: DockerFile.dev
    image: img_app_dev:1.0
    restart: always
    container_name: ctr_app_dev
    ports:
      - "8081:8081"   #Interfas Web
      - "19000:19000" #Metro Bundler
      - "19001:19001" #WebSocket
      - "19002:19002" #Expo Dev Tools
    environment:
      - TZ=America/Mexico_City
    volumes:
      - ./app:/client:rw,uid=1000,gid=1000 
    networks:
      - net_app_dev

    command: /bin/bash -c "if [ ! -d node_modules ]; then npm install; fi && tail -f /dev/null"

networks:
  net_app_dev:
    name: net_app_dev
    driver: bridge

