# Usar Node.js versión 22 como imagen base
FROM node:22

# Cambiar al usuario node
USER node

# Establecer directorio de trabajo
WORKDIR /client

# Copiar los archivos del proyecto al contenedor
COPY --chown=node:node . /clientq

# Exponer los puertos necesarios
EXPOSE 8081 19000 19001 19002
